schemas:
  bootstrap: 8000
  fahrradinitiativen: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://fahrradinitiativen.leanlabs.de/themes/fahrradinitiativen/favicon.ico'
  use_default: 1
features:
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
  node_user_picture: 0
logo:
  path: ''
  url: ''
  use_default: 1
breadcrumb: '0'
region_wells:
  navigation: ''
  navigation_collapsible: ''
  header: ''
  highlighted: ''
  help: ''
  content: ''
  sidebar_first: ''
  sidebar_second: well
  footer: ''
  mobile_menu: ''
  mobile_quicklinks: ''
table_responsive: '-1'
modal_enabled: 0
popover_enabled: 0
tooltip_enabled: 0
table: ''
langcode: de
